//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được phép trùng.
        /// </summary>
        public static string ErrorService_DuplicateEmployeeCode {
            get {
                return ResourceManager.GetString("ErrorService_DuplicateEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số chứng minh thư nhân dân không được phép trùng.
        /// </summary>
        public static string ErrorService_DuplicateEmployeeIdentifyNumber {
            get {
                return ResourceManager.GetString("ErrorService_DuplicateEmployeeIdentifyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại nhân viên không được phép trùng.
        /// </summary>
        public static string ErrorService_DuplicateEmployeePhoneNumber {
            get {
                return ResourceManager.GetString("ErrorService_DuplicateEmployeePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đơn vị không được phép để trống.
        /// </summary>
        public static string ErrorService_EmptyDepartment {
            get {
                return ResourceManager.GetString("ErrorService_EmptyDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên không được phép để trống.
        /// </summary>
        public static string ErrorService_EmptyEmployeeCode {
            get {
                return ResourceManager.GetString("ErrorService_EmptyEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email nhân viên không được phép để trống.
        /// </summary>
        public static string ErrorService_EmptyEmployeeEmail {
            get {
                return ResourceManager.GetString("ErrorService_EmptyEmployeeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên nhân viên không được phép để trống.
        /// </summary>
        public static string ErrorService_EmptyEmployeeFullName {
            get {
                return ResourceManager.GetString("ErrorService_EmptyEmployeeFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số chứng minh nhân dân nhân viên không được phép để trống.
        /// </summary>
        public static string ErrorService_EmptyEmployeeIdentifyNumber {
            get {
                return ResourceManager.GetString("ErrorService_EmptyEmployeeIdentifyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại nhân viên không được phép để trống.
        /// </summary>
        public static string ErrorService_EmptyEmployeePhoneNumber {
            get {
                return ResourceManager.GetString("ErrorService_EmptyEmployeePhoneNumber", resourceCulture);
            }
        }
    }
}
